# Generated by Django 5.2.5 on 2025-09-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='resume',
            name='ats_score',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='file',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='grammar_score',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='parsed_data',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='raw_text',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='status',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
        migrations.AddField(
            model_name='resume',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume1'),
        ),
    ]
